<?xml version="1.0" encoding="utf-8"?><Database Name="db_Banner" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Account" Member="Account">
    <Type Name="Account">
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Name_First" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name_Last" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDNumber" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IDType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EducationType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JobType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarriageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarriageNote" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BaptizedType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BackUsedFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TeacherFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OldID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Account_Bank" Member="Account_Bank" ThisKey="ACID" OtherKey="ACID" Type="Account_Bank" />
      <Association Name="Account_Account_Note" Member="Account_Note" ThisKey="ACID" OtherKey="ACID" Type="Account_Note" />
      <Association Name="Account_Account_Performance" Member="Account_Performance" ThisKey="ACID" OtherKey="ACID" Type="Account_Performance" />
      <Association Name="Account_Baptized" Member="Baptized" ThisKey="ACID" OtherKey="ACID" Type="Baptized" />
      <Association Name="Account_Community" Member="Community" ThisKey="ACID" OtherKey="ACID" Type="Community" />
      <Association Name="Account_Coupon_Account" Member="Coupon_Account" ThisKey="ACID" OtherKey="ACID" Type="Coupon_Account" />
      <Association Name="Account_Family" Member="Family" ThisKey="ACID" OtherKey="ACID" Type="Family" />
      <Association Name="Account_JoinGroupWish" Member="JoinGroupWish" ThisKey="ACID" OtherKey="ACID" Type="JoinGroupWish" />
      <Association Name="Account_M_ML_Account" Member="M_ML_Account" ThisKey="ACID" OtherKey="ACID" Type="M_ML_Account" />
      <Association Name="Account_M_O_Account" Member="M_O_Account" ThisKey="ACID" OtherKey="ACID" Type="M_O_Account" />
      <Association Name="Account_M_OI_Account" Member="M_OI_Account" ThisKey="ACID" OtherKey="ACID" Type="M_OI_Account" />
      <Association Name="Account_M_OI2_Account" Member="M_OI2_Account" ThisKey="ACID" OtherKey="ACID" Type="M_OI2_Account" />
      <Association Name="Account_M_Rool_Account" Member="M_Rool_Account" ThisKey="ACID" OtherKey="ACID" Type="M_Rool_Account" />
      <Association Name="Account_Order_Header" Member="Order_Header" ThisKey="ACID" OtherKey="ACID" Type="Order_Header" />
      <Association Name="Account_OrganizeInfo" Member="OrganizeInfo" ThisKey="ACID" OtherKey="ACID" Type="OrganizeInfo" />
    </Type>
  </Table>
  <Table Name="dbo.ZipCode" Member="ZipCode">
    <Type Name="ZipCode">
      <Column Name="ZID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ZipCode_Location" Member="Location" ThisKey="ZID" OtherKey="ZID" Type="Location" />
    </Type>
  </Table>
  <Table Name="dbo.Account_Bank" Member="Account_Bank">
    <Type Name="Account_Bank">
      <Column Name="ABID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Account_Bank" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
      <Association Name="Bank_Account_Bank" Member="Bank" ThisKey="BID" OtherKey="BID" Type="Bank" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account_Note" Member="Account_Note">
    <Type Name="Account_Note">
      <Column Name="ANID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoteType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Account_Note" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account_Performance" Member="Account_Performance">
    <Type Name="Account_Performance">
      <Column Name="APID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Performance" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SortNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Account_Performance" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bank" Member="Bank">
    <Type Name="Bank">
      <Column Name="BID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Bank_Account_Bank" Member="Account_Bank" ThisKey="BID" OtherKey="BID" Type="Account_Bank" />
    </Type>
  </Table>
  <Table Name="dbo.Baptized" Member="Baptized">
    <Type Name="Baptized">
      <Column Name="BID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BaptismDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ImplementFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Baptized" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Community" Member="Community">
    <Type Name="Community">
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommunityType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommunityValue" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="Account_Community" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contect" Member="Contect">
    <Type Name="Contect">
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TargetType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContectType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContectValue" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="CheckFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CheckDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Coupon_Account" Member="Coupon_Account">
    <Type Name="Coupon_Account">
      <Column Name="CAID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OPID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Coupon_Account" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
      <Association Name="Coupon_Header_Coupon_Account" Member="Coupon_Header" ThisKey="CHID" OtherKey="CHID" Type="Coupon_Header" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Coupon_Header" Member="Coupon_Header">
    <Type Name="Coupon_Header">
      <Column Name="CHID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price_Cut" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Coupon_Header_Coupon_Account" Member="Coupon_Account" ThisKey="CHID" OtherKey="CHID" Type="Coupon_Account" />
      <Association Name="Product_Coupon_Header" Member="Product" ThisKey="PID" OtherKey="PID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Course">
    <Type Name="Course">
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CourseType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TargetInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GraduationInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClassicalFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_Course_Rool" Member="Course_Rool" ThisKey="CID" OtherKey="CID" Type="Course_Rool" />
      <Association Name="Course_Product" Member="Product" ThisKey="CID" OtherKey="CID" Type="Product" />
      <Association Name="Course_Category_Course" Member="Course_Category" ThisKey="CCID" OtherKey="CCID" Type="Course_Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course_Category" Member="Course_Category">
    <Type Name="Course_Category">
      <Column Name="CCID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_Category_Course" Member="Course" ThisKey="CCID" OtherKey="CCID" Type="Course" />
    </Type>
  </Table>
  <Table Name="dbo.Course_Rool" Member="Course_Rool">
    <Type Name="Course_Rool">
      <Column Name="CRID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetInt1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetInt2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_Course_Rool" Member="Course" ThisKey="CID" OtherKey="CID" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Event">
    <Type Name="Event">
      <Column Name="EID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ECID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EventType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CircleFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="WeeklyNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="ETime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="SDate_AllowJoin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EDate_AllowJoin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="STime_AllowJoin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="ETime_AllowJoin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Location_MID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location_URL" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Location_Note" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Event_Event_Join_Header" Member="Event_Join_Header" ThisKey="EID" OtherKey="EID" Type="Event_Join_Header" />
      <Association Name="Event_Category_Event" Member="Event_Category" ThisKey="ECID" OtherKey="ECID" Type="Event_Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event_Category" Member="Event_Category">
    <Type Name="Event_Category">
      <Column Name="ECID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Event_Category_Event" Member="Event" ThisKey="ECID" OtherKey="ECID" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Event_Join_Detail" Member="Event_Join_Detail">
    <Type Name="Event_Join_Detail">
      <Column Name="EJDID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EJHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Event_Join_Header_Event_Join_Detail" Member="Event_Join_Header" ThisKey="EJHID" OtherKey="EJHID" Type="Event_Join_Header" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event_Join_Header" Member="Event_Join_Header">
    <Type Name="Event_Join_Header">
      <Column Name="EJHID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Event_Join_Header_Event_Join_Detail" Member="Event_Join_Detail" ThisKey="EJHID" OtherKey="EJHID" Type="Event_Join_Detail" />
      <Association Name="Event_Event_Join_Header" Member="Event" ThisKey="EID" OtherKey="EID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Family" Member="Family">
    <Type Name="Family">
      <Column Name="FID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDNumber" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FamilyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FamilyTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TargetACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Account_Family" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JoinGroupWish" Member="JoinGroupWish">
    <Type Name="JoinGroupWish">
      <Column Name="JGWID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JoinType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeeklyNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_JoinGroupWish" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="Location">
    <Type Name="Location">
      <Column Name="LID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TargetType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="ZipCode_Location" Member="ZipCode" ThisKey="ZID" OtherKey="ZID" Type="ZipCode" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_ML_Account" Member="M_ML_Account">
    <Type Name="M_ML_Account">
      <Column Name="MID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MLID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_M_ML_Account" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
      <Association Name="Meeting_Location_M_ML_Account" Member="Meeting_Location" ThisKey="MLID" OtherKey="MLID" Type="Meeting_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_O_Account" Member="M_O_Account">
    <Type Name="M_O_Account">
      <Column Name="MID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_M_O_Account" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
      <Association Name="Organize_M_O_Account" Member="Organize" ThisKey="OID" OtherKey="OID" Type="Organize" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_OI_Account" Member="M_OI_Account">
    <Type Name="M_OI_Account">
      <Column Name="MID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LeaveDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_M_OI_Account" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
      <Association Name="OrganizeInfo_M_OI_Account" Member="OrganizeInfo" ThisKey="OIID" OtherKey="OIID" Type="OrganizeInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_OI2_Account" Member="M_OI2_Account">
    <Type Name="M_OI2_Account">
      <Column Name="MID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_M_OI2_Account" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
      <Association Name="OrganizeInfo_M_OI2_Account" Member="OrganizeInfo" ThisKey="OIID" OtherKey="OIID" Type="OrganizeInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_Product_Teacher" Member="M_Product_Teacher">
    <Type Name="M_Product_Teacher">
      <Column Name="MID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_M_Product_Teacher" Member="Product" ThisKey="PID" OtherKey="PID" Type="Product" IsForeignKey="true" />
      <Association Name="Product_Class_M_Product_Teacher" Member="Product_Class" ThisKey="PCID" OtherKey="PCID" Type="Product_Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_Rool_Account" Member="M_Rool_Account">
    <Type Name="M_Rool_Account">
      <Column Name="MID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LeaveDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_M_Rool_Account" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
      <Association Name="Rool_M_Rool_Account" Member="Rool" ThisKey="RID" OtherKey="RID" Type="Rool" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_Rool_Menu" Member="M_Rool_Menu">
    <Type Name="M_Rool_Menu">
      <Column Name="MPMID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShowFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AddFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EditFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrintFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UploadFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Menu_M_Rool_Menu" Member="Menu" ThisKey="MID" OtherKey="MID" Type="Menu" IsForeignKey="true" />
      <Association Name="Rool_M_Rool_Menu" Member="Rool" ThisKey="RID" OtherKey="RID" Type="Rool" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Meeting_Location" Member="Meeting_Location">
    <Type Name="Meeting_Location">
      <Column Name="MLID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Meeting_Location_M_ML_Account" Member="M_ML_Account" ThisKey="MLID" OtherKey="MLID" Type="M_ML_Account" />
      <Association Name="Meeting_Location_Meeting_Location_Set" Member="Meeting_Location_Set" ThisKey="MLID" OtherKey="MLID" Type="Meeting_Location_Set" />
    </Type>
  </Table>
  <Table Name="dbo.Meeting_Location_Set" Member="Meeting_Location_Set">
    <Type Name="Meeting_Location_Set">
      <Column Name="MLSID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MLID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SetType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeeklyNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="S_hour" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="S_minute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="E_hour" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="E_minute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Meeting_Location_Set_Meeting_Location_Used" Member="Meeting_Location_Used" ThisKey="MLSID" OtherKey="MLSID" Type="Meeting_Location_Used" />
      <Association Name="Meeting_Location_Meeting_Location_Set" Member="Meeting_Location" ThisKey="MLID" OtherKey="MLID" Type="Meeting_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Meeting_Location_Used" Member="Meeting_Location_Used">
    <Type Name="Meeting_Location_Used">
      <Column Name="MLUID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MLSID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="S_DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="E_DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JoinCt_Child" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JoinCt_Juiner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JoinCt_Aldult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Meeting_Location_Set_Meeting_Location_Used" Member="Meeting_Location_Set" ThisKey="MLSID" OtherKey="MLSID" Type="Meeting_Location_Set" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menu">
    <Type Name="Menu">
      <Column Name="MID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ImgURL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SortNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Menu_M_Rool_Menu" Member="M_Rool_Menu" ThisKey="MID" OtherKey="MID" Type="M_Rool_Menu" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Header" Member="Order_Header">
    <Type Name="Order_Header">
      <Column Name="OHID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Order_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Header_Order_Paid" Member="Order_Paid" ThisKey="OHID" OtherKey="OHID" Type="Order_Paid" />
      <Association Name="Order_Header_Order_Product" Member="Order_Product" ThisKey="OHID" OtherKey="OHID" Type="Order_Product" />
      <Association Name="Account_Order_Header" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Paid" Member="Order_Paid">
    <Type Name="Order_Paid">
      <Column Name="OPID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaidType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaidFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PaidDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TradeNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TradeAmt" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PayAmt" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Order_Paid_Order_PaidDetail" Member="Order_PaidDetail" ThisKey="OPID" OtherKey="OPID" Type="Order_PaidDetail" />
      <Association Name="Order_Header_Order_Paid" Member="Order_Header" ThisKey="OHID" OtherKey="OHID" Type="Order_Header" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_PaidDetail" Member="Order_PaidDetail">
    <Type Name="Order_PaidDetail">
      <Column Name="OPDID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OPID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OPDType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Order_Paid_Order_PaidDetail" Member="Order_Paid" ThisKey="OPID" OtherKey="OPID" Type="Order_Paid" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Product" Member="Order_Product">
    <Type Name="Order_Product">
      <Column Name="OPID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CAID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price_Basic" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price_Finally" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Header_Order_Product" Member="Order_Header" ThisKey="OHID" OtherKey="OHID" Type="Order_Header" IsForeignKey="true" />
      <Association Name="Product_Class_Order_Product" Member="Product_Class" ThisKey="PCID" OtherKey="PCID" Type="Product_Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organize" Member="Organize">
    <Type Name="Organize">
      <Column Name="OID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Organize_M_O_Account" Member="M_O_Account" ThisKey="OID" OtherKey="OID" Type="M_O_Account" />
      <Association Name="Organize_OrganizeInfo" Member="OrganizeInfo" ThisKey="OID" OtherKey="OID" Type="OrganizeInfo" />
    </Type>
  </Table>
  <Table Name="dbo.OrganizeInfo" Member="OrganizeInfo">
    <Type Name="OrganizeInfo">
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BusinessType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OldID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="OrganizeInfo_M_OI_Account" Member="M_OI_Account" ThisKey="OIID" OtherKey="OIID" Type="M_OI_Account" />
      <Association Name="OrganizeInfo_M_OI2_Account" Member="M_OI2_Account" ThisKey="OIID" OtherKey="OIID" Type="M_OI2_Account" />
      <Association Name="OrganizeInfo_Product" Member="Product" ThisKey="OIID" OtherKey="OIID" Type="Product" />
      <Association Name="Account_OrganizeInfo" Member="Account" ThisKey="ACID" OtherKey="ACID" Type="Account" IsForeignKey="true" />
      <Association Name="Organize_OrganizeInfo" Member="Organize" ThisKey="OID" OtherKey="OID" Type="Organize" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Product">
    <Type Name="Product">
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TargetInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GraduationInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="YearNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EchelonNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImgURL" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Price_Basic" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price_Early" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SDate_Signup_OnSite" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EDate_Signup_OnSite" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SDate_Signup_OnLine" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EDate_Signup_OnLine" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SDate_Early" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EDate_Early" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ShowFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Coupon_Header" Member="Coupon_Header" ThisKey="PID" OtherKey="PID" Type="Coupon_Header" />
      <Association Name="Product_M_Product_Teacher" Member="M_Product_Teacher" ThisKey="PID" OtherKey="PID" Type="M_Product_Teacher" />
      <Association Name="Product_Product_Class" Member="Product_Class" ThisKey="PID" OtherKey="PID" Type="Product_Class" />
      <Association Name="Product_Product_File" Member="Product_File" ThisKey="PID" OtherKey="PID" Type="Product_File" />
      <Association Name="Product_Product_Rool" Member="Product_Rool" ThisKey="PID" OtherKey="PID" Type="Product_Rool" />
      <Association Name="Course_Product" Member="Course" ThisKey="CID" OtherKey="CID" Type="Course" IsForeignKey="true" />
      <Association Name="OrganizeInfo_Product" Member="OrganizeInfo" ThisKey="OIID" OtherKey="OIID" Type="OrganizeInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Class" Member="Product_Class">
    <Type Name="Product_Class">
      <Column Name="PCID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoopFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TargetDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="WeeklyNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="ETime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="PeopleCt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="MeetURL" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Class_M_Product_Teacher" Member="M_Product_Teacher" ThisKey="PCID" OtherKey="PCID" Type="M_Product_Teacher" />
      <Association Name="Product_Class_Order_Product" Member="Order_Product" ThisKey="PCID" OtherKey="PCID" Type="Order_Product" />
      <Association Name="Product_Product_Class" Member="Product" ThisKey="PID" OtherKey="PID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_File" Member="Product_File">
    <Type Name="Product_File">
      <Column Name="PFID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileURL" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="DownloadFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Product_File" Member="Product" ThisKey="PID" OtherKey="PID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Rool" Member="Product_Rool">
    <Type Name="Product_Rool">
      <Column Name="PRID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CRID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetInt1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetInt2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Product_Rool" Member="Product" ThisKey="PID" OtherKey="PID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rool" Member="Rool">
    <Type Name="Rool">
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoolType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Rool_M_Rool_Account" Member="M_Rool_Account" ThisKey="RID" OtherKey="RID" Type="M_Rool_Account" />
      <Association Name="Rool_M_Rool_Menu" Member="M_Rool_Menu" ThisKey="RID" OtherKey="RID" Type="M_Rool_Menu" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teacher">
    <Type Name="Teacher">
      <Column Name="TID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SaveACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.v_GetAC_O2_OI" Member="v_GetAC_O2_OI">
    <Type Name="v_GetAC_O2_OI">
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_First" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name_Last" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_GetAC_OITree" Member="v_GetAC_OITree">
    <Type Name="v_GetAC_OITree">
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_First" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name_Last" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OITitle_10" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_10" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OID_10" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OITitle_9" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle_8" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle_7" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle_6" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle_5" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle_4" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle_3" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle_2" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OITitle_1" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="OIID_1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OID_1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetOI2List" Method="sp_GetOI2List">
    <Parameter Name="ACID" Parameter="aCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetOI2ListResult">
      <Column Name="OIID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetOI2_ACList" Method="sp_GetOI2_ACList">
    <Parameter Name="ACID" Parameter="aCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetOI2_ACListResult">
      <Column Name="ACID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_First" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name_Last" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>